FROM golang
WORKDIR /go/src/github.com/abstractart/hello-world
EXPOSE 40000

RUN go mod init github.com/abstractart/hello-world
RUN go get github.com/go-delve/delve/cmd/dlv
ADD ./main.go .

CMD [ "dlv", "debug", "github.com/abstractart/hello-world", "--listen=:40000", "--headless=true", "--api-version=2", "--log" ]
